version: '3.8'
services:  
  aws-proxy:
    container_name: aws-proxy
    image: aws-proxy
    environment:
      - NODE_ENV=local
      - PORT=5000
      - AWS_REGION=eu-west-1
      - USE_MINIO_OBJECT_STORE=true
      - AWS_ACCESS_KEY=minioadmin
      - AWS_SECRET_KEY=minioadmin
      - AWS_S3_ENDPOINT=http://minio:9000
    ports:
      - 5000:5000
    networks:
      - aws-proxy  

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      - aws-proxy  

volumes:  
  minio-data:
    driver: local

networks:
  aws-proxy:
    driver: bridge
